### ISSUE TITLE
ConfigError: Failed to look up latest Fairy-Stockfish release (status 404)

### ISSUE THREAD

**Issue by SriMethan** [TheYoBots/lishoginet#4]
logs : -
![image](https://user-images.githubusercontent.com/77402282/228773703-12d98652-b37c-4268-aef7-40e470fc73d4.png)

**Comment by TheYoBots** [comment]
Hi,
I suggest you use the official shoginet client ( https://github.com/WandererXII/shoginet ). This was originally made to test if I could increase the speed of lishogi's AI... but I just made it slower.

Anyways, if you still want to use this, you'll have to change this line:
https://github.com/TheYoBots/lishoginet/blob/e57d2f694bdb864860025e9d2abf5d3f57196e3d/lishoginet.py#L107

to something like this:
```py
STOCKFISH_RELEASES = "https://api.github.com/repos/fairy-stockfish/Fairy-Stockfish/releases/latest"
```

Over here I'm not going to make that change though because I recommend to use the official client https://github.com/WandererXII/shoginet

**Comment by SriMethan** [comment]
Okay, Thanks.
